### ISSUE TITLE
Loading Waveform Data with np.load('')

### ISSUE THREAD

**Issue by glenn-jocher** [kcroker/lappd_digest#2]
Tried to load like this from within popecki adapter branch, but missing another module. Error message is `ModuleNotFoundError: No module named 'bitstruct'

To reproduce:
```python
import numpy as np
x=np.load('incom_pickles/incom12_18122019-114832_1339', allow_pickle=True)
```

<img width="1470" alt="Screen Shot 2020-08-08 at 3 37 17 PM" src="https://user-images.githubusercontent.com/26833433/89721756-50ac1c80-d996-11ea-8608-2e7e193b0ace.png">

**Comment by kcroker** [comment]
that one is in the readme

**Comment by glenn-jocher** [comment]
I see readme instructions in the popecki branch now! Closing issue.
